// 自动生成：scripts/build-guide-photos.mjs（清单在 scripts/guide-photos.json）。不要手改。
//
// 每张照片带着自己的三语 alt 与一句图说：照片放到哪一章，说明就跟到哪一章，
// 不会出现空 alt，也不会把 alt 抄成一段长图说。
// source: "wikimedia" 按 CC 条件署名；source: "official" 只写来源页与提供方。
import type { L10n } from "./trip-data";

export type GuidePhoto = {
  key: string;
  file: string;
  width: number;
  height: number;
  title: string;
  artist: string;
  license: string;
  licenseUrl?: string;
  page: string;
  source: "wikimedia" | "official";
  alt: L10n;
  caption: L10n;
};

export const GUIDE_PHOTOS: GuidePhoto[] = [
  {"key":"pazhou-pagoda","file":"images/pazhou-pagoda.jpg","width":1400,"height":933,"title":"Aerial View, Whampoa Pagoda, Guangzhou 20230701.jpg","artist":"Tim Wu","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0/","page":"https://commons.wikimedia.org/wiki/File:Aerial_View,_Whampoa_Pagoda,_Guangzhou_20230701.jpg","source":"wikimedia","alt":{"zh":"航拍琶洲塔：八角形的砖塔立在一片树林中间，四周是住宅楼、会展与交易中心的新楼，天上压着一层乌云。","en":"An aerial view of the Pazhou pagoda: an octagonal brick tower standing in a block of trees, ringed by flats and new exhibition and trading buildings under a dark sky.","ar":"منظر جوي لباغودا بازو: برج من الآجر ثماني الأضلاع يقف وسط بقعة من الأشجار، تحيط به مبانٍ سكنية وأبراج معارض وتجارة حديثة تحت سماء داكنة."},"caption":{"zh":"琶洲塔与今天的城区在同一个画面里。","en":"The Pazhou pagoda and today's district in one frame.","ar":"باغودا بازو والحيّ الحديث في إطار واحد."}},
  {"key":"huaisheng-minaret","file":"images/huaisheng-minaret.jpg","width":600,"height":400,"title":"怀圣寺光塔","artist":"广州越秀发布","license":"来源页","page":"https://www.yuexiu.gov.cn/zjyx/yxjd/zjwh/content/post_8665060.html","source":"official","alt":{"zh":"从院子里抬头看：白色的圆筒形光塔立在蓝天下，近处是一排绿琉璃瓦的中式屋檐和树。","en":"Looking up from the courtyard: the white cylindrical minaret against a blue sky, with green-tiled Chinese eaves and trees in the foreground.","ar":"نظرة إلى الأعلى من الفناء: المئذنة الأسطوانية البيضاء في سماء زرقاء، وفي المقدّمة أفاريز صينية بقرميد أخضر وأشجار."},"caption":{"zh":"怀圣寺：白色的光塔从中式屋檐旁升起来。","en":"Huaisheng Mosque: the white minaret rising beside Chinese eaves.","ar":"مسجد هوايشنغ: المئذنة البيضاء ترتفع إلى جانب الأفاريز الصينية."}},
  {"key":"xianxian-gate","file":"images/xianxian-gate.jpg","width":1400,"height":1050,"title":"Guangzhou Yuexiu Qingzhen Xianxian Gumu 2023-07-26 12.12.55.jpg","artist":"古海岸遗址","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0/","page":"https://commons.wikimedia.org/wiki/File:Guangzhou_Yuexiu_Qingzhen_Xianxian_Gumu_2023-07-26_12.12.55.jpg","source":"wikimedia","alt":{"zh":"灰砖的门楼，檐下有彩绘，门额上并排着阿拉伯文和「清真先贤古墓」六个字，中间是圆形的月洞门，两旁是老树和盆栽。","en":"A grey brick gateway with painted eaves: an Arabic inscription and the Chinese name of the ancient tomb side by side above a round moon gate, old trees and potted plants on either side.","ar":"بوابة من الآجر الرمادي بأفاريز مزخرفة: نقش عربي واسم المقبرة بالصينية جنبًا إلى جنب فوق بوابة مستديرة، وعلى الجانبين أشجار عتيقة ونباتات في أصص."},"caption":{"zh":"先贤古墓的门楼，门额上是阿拉伯文与汉字。","en":"The gateway to the ancient tomb, inscribed in Arabic and Chinese.","ar":"بوابة المقبرة القديمة، ونقشها بالعربية والصينية."}},
  {"key":"parc-garden","file":"images/parc-garden.jpg","width":1400,"height":933,"title":"Aerial View, Parc Central, Guangzhou 20230520-C.jpg","artist":"Tim Wu","license":"CC BY-SA 4.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/4.0/","page":"https://commons.wikimedia.org/wiki/File:Aerial_View,_Parc_Central,_Guangzhou_20230520-C.jpg","source":"wikimedia","alt":{"zh":"垂直俯看天环广场：两片弧形的格栅屋顶像两条鱼，中间留出步道、绿化和下沉广场，四周是车流不断的马路。","en":"Parc Central seen straight down: two curved latticed roofs like a pair of fish, with walkways, planting and a sunken plaza left open between them, busy roads all around.","ar":"بارك سنترال من الأعلى مباشرة: سقفان مقوّسان مشبّكان كسمكتين، وبينهما ممرات ومساحات خضراء وساحة منخفضة، وحولهما شوارع مزدحمة."},"caption":{"zh":"天环：两片屋顶之间留着花园、步道和下沉广场。","en":"Parc Central: garden, walkways and a sunken plaza between the two roofs.","ar":"بارك سنترال: حديقة وممرات وساحة منخفضة بين السقفين."}},
  {"key":"gxr-guangzhou","file":"images/gxr-guangzhou.jpg","width":1400,"height":933,"title":"WeRide GXR robotaxi in Guangzhou","artist":"WeRide 文远知行","license":"来源页","page":"https://ir.weride.ai/news-releases/news-release-details/weride-launches-247-fully-driverless-robotaxi-service-guangzhous","source":"official","alt":{"zh":"一辆黑色的自动驾驶出租车驶过绿灯路口，车顶装着一排传感器，车身印着文远知行的标识，挂新能源绿牌。","en":"A black self-driving taxi crossing a junction on green, a row of sensors on its roof, the WeRide logo on its body and a green electric-vehicle plate.","ar":"سيارة أجرة سوداء ذاتية القيادة تعبر تقاطعًا والإشارة خضراء، وعلى سقفها صفّ من أجهزة الاستشعار، وعلى جسمها شعار WeRide ولوحة خضراء للسيارات الكهربائية."},"caption":{"zh":"文远知行的 GXR 行驶在广州街头。","en":"A WeRide GXR on the road in Guangzhou.","ar":"سيارة GXR من WeRide في شوارع قوانغتشو."}},
  {"key":"hotel-lift-robot","file":"images/hotel-lift-robot.jpg","width":960,"height":1040,"title":"Hospitality room delivery robot","artist":"Pudu Robotics 普渡机器人","license":"来源页","page":"https://www.pudurobotics.com/en/solutions/hospitality","source":"official","alt":{"zh":"一台白色的送物机器人正从电梯口出来，柜门分成四格，脚下是酒店的大理石地面。","en":"A white delivery robot coming out of a lift doorway, its cabinet split into four hatches, marble hotel flooring underneath.","ar":"روبوت توصيل أبيض يخرج من باب مصعد، وخزانته مقسّمة إلى أربع فتحات، وتحته أرضية رخامية في فندق."},"caption":{"zh":"酒店服务示例：送物机器人进出电梯。","en":"Hotel service example: a delivery robot using a lift.","ar":"مثال على خدمة فندقية: روبوت توصيل يستخدم المصعد."}},
  {"key":"pazhou-drone","file":"images/pazhou-drone.jpg","width":1348,"height":745,"title":"琶洲低空配送","artist":"广州市海珠区人民政府","license":"来源页","page":"https://www.haizhu.gov.cn/hzdt/ztlm/dkjj/hhr/cjhx/content/post_10678783.html","source":"official","alt":{"zh":"垂直俯看：一条绿色的河涌横过画面，一架白色多旋翼无人机停在岸边的设施上方，两侧是树、马路和排成一列的电动车。","en":"Seen straight down: a green water channel crossing the frame, a white multirotor drone hovering over a small facility on the bank, trees, a road and rows of scooters on either side.","ar":"من الأعلى مباشرة: قناة مائية خضراء تعبر الصورة، وطائرة مسيّرة بيضاء متعدّدة المراوح تحلّق فوق منشأة صغيرة على الضفة، وعلى الجانبين أشجار وشارع وصفوف من الدراجات الكهربائية."},"caption":{"zh":"琶洲的低空配送：无人机沿着河涌上方走。","en":"Low-altitude delivery in Pazhou: the drone follows the water channel.","ar":"توصيل منخفض الارتفاع في بازو: المسيّرة تتبع مجرى القناة."}},
  {"key":"miniso-land","file":"images/miniso-land.jpg","width":1400,"height":788,"title":"正佳广场 MINISO LAND 广州壹号店开业","artist":"信息时报记者 潘敬文","license":"来源页","page":"https://xxsb.gz-cmc.com/pages/2026/01/30/afa451fb749c44af8dcef00ce3abdf5a.html","source":"official","alt":{"zh":"正佳广场的外墙被一整面绿底红边的 MINISO 装置盖住，中间是一座高高的拱门，上面挂着 MINISO 招牌和一排卡通角色；门前站满了人，很多人举着手机在拍，远处是几栋玻璃幕墙的高楼。","en":"The outside wall of Grandview Mall covered by a giant green-and-red MINISO installation, a tall decorated archway in the middle carrying the MINISO sign and a row of cartoon characters; a crowd stands in front, many of them holding up phones, and glass towers rise behind.","ar":"جدار غراندفيو مول الخارجي تغطّيه منشأة ضخمة لـ«ميني سو» بالأخضر والأحمر، وفي وسطها قوس مرتفع مزيّن يحمل لافتة «ميني سو» وصفًّا من الشخصيات الكرتونية؛ وأمامها يقف حشد من الناس يرفع كثيرون منهم هواتفهم، وخلفها أبراج زجاجية."},"caption":{"zh":"开业那天的正佳广场门口。","en":"Outside Grandview Mall on the morning it opened.","ar":"أمام غراندفيو مول صباح الافتتاح."}},
];
